### ISSUE TITLE
Improve or remove OTOBO::Perl::ObjectDependencies

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/CodePolicy#63]
The Perl::Tidy check `OTOBO::Perl::ObjectDependencies` currently works like this:

1. extract all module names that are used in a call to `$Kernel::OM->Get()`
2.  find all module names declared in `our @ObjectDependencies`
3. look for undeclared modules
4. report undeclared modules

This works, but it does not really make sense. Let's take a look at _Kernel/System/User/Preferences/DB.pm_. There we have     Kernel::Config and Kernel::System::Cache in `@ObjectDependencies`. When Kernel::Config is discarded then K::S::U::P::DB must be discarded to, as e.g. in `new` the attribute `$Self->{PreferencesTable}` is set from the config object. Thus Kernel::Config is a real dependency. But when `Kernel::System::Cache` then K::S::U::P::DB doesn't have to be discarded. The methods `SetPreferences()` and `GetPreferences()` happily do their thing, creating a cache object when they need it.

I propose to simplify the check. Whenever `$Kernel::OM->Get()`is found in the code, then there must be the `@ObjectDependencies` array. The array can be empty. The content of the array is not checked by the policy, it's the responsibility of the developer.

**Comment by svenoe** [comment]
The thing is that for your suggestion every developer has to be aware of what the purpose of ObjectDependencies is, that is, know exactly how `$Kernel::OM` works. The errors which potentially occur if this is missing at a spot where it is needed are probably a nightmare to debug.

On the other hand, as the CodePolicy provides the exact list of Modules which currently needs to be present (nicely ordered and with the correct indentation), the effort to put in the list of modules is basically one copy&paste.

I see that in practice, in most cases it is an unnecessary nuisance - but in my eyes it is a minor one, and probably worth it to not fall into difficult to find traps... For cases where ObjectDependencies are problematic, we can still use `## nofilter(TidyAll::Plugin::OTOBO::Perl::ObjectDependencies)` - not to encourage you to use this everywhere, because you know what you are doing. ;)

**Comment by bschmalhofer** [comment]
I accept your argument. But I still see it as a bad thing to make developers do funny things even if they know better. The sad thing is that this mess is self-inflicted. There is no good justification that the OM works the way it works now. First the OM artificially expands the scopes and lifetime of objects that are usually only needed in a specific context. Then it burdens the developers with having to think about how to manage these objects. But I still have the hope that some day a better solution will be implemented for OTOBO.

I propose that I add some explanation to the policy, but leave the current functionality in place.

**Comment by bschmalhofer** [comment]
The request has been handled in #64 . Closing this issue.
