### ISSUE TITLE
Make bin/scripts/install-git-hooks.pl work together with the comand Dev::Git::InstallHooks

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/CodePolicy#8]
Looks like install-git-hooks.pl overwrites existing hooks. Is there an easy way to merge git hooks?

**Comment by bschmalhofer** [comment]
I looked at the files that are in conflict. In the otobo sandbox there only is _Kernel/System/Console/Command/Dev/Git/InstallHooks/prepare-commit-msg.dist_ . This hook conflicts with _Kernel/TidyAll/git-hooks/prepare-commit-msg.pl_ .  The feature in prepare-commit-msg.pl is not very interesting. AFAIK there is not process that generated the file  _git/OTOBOCommitTemplate.msg_ . On the other hand, the hook in otobo provides a real benefit, but it is unfortunate that there are two sources of git hooks.

Therefore I propose:

- [ ] remove support for git hooks in OTOBO itself, including ./Kernel/System/Console/Command/Dev/Git/InstallHooks
- [ ] merge the functionality of _prepare-commit-msg.dist_ into prepare-commit-msg.pl 

@svenoe : What do you think ?

**Comment by svenoe** [comment]
As I understand it, the current functionality would be to prepend 'Issue #xxx:' depending on the branch name to commits. This is definitely good for the general structure. One question would be, whether everyone who develops is having CodePolicy installed or not.

As I see the current state, the OTOBO-version of this is more for OTOBO development, the CodePolicy-version is for package development, and much more general. I think both is making sense, somewhat.

From my perspective we should feel free to adjust this stuff to our liking. Especially with docker, we have another place where we can prepare some sort of environment to standardize development a bit more. We should keep in mind both package-, as well as OTOBO-development.

(This is not a totally direct answer to both points, because I'm a bit unsure... I will think about it some more.)

**Comment by bschmalhofer** [comment]
The main point here is to avoid confusion with having two source of git hooks. Developers who don't want to bother with "installing" CodePolicy can always be pointed directly to  https://github.com/RotherOSS/CodePolicy/blob/master/Kernel/TidyAll/git-hooks/prepare-commit-msg.pl .

**Comment by bschmalhofer** [comment]
The prepare-commit-msg hook is adapted. The respective hook in the otobo repository is removed. Closing this issue.
